In [2]:
import pandas as pd
complaints = pd.read_csv("complaints.csv")
customers = pd.read_csv("customers.csv")
transactions = pd.read_csv("transactions.csv")
accounts = pd.read_csv("accounts.csv")

In [3]:
accounts.head()

,account_id,customer_id,account_number,account_type,currency,current_balance,opened_date
0,2b65ee56-991e-4377-9395-69f29ca99cb5,b5af208d-1d66-44d8-81c5-92883eb9b77c,3563730273,savings,NGN,1643906.15,2025-06-07
1,485638ae-1b64-442a-a1b7-37bb58823863,b5af208d-1d66-44d8-81c5-92883eb9b77c,1195742845,current,NGN,5610762.16,2024-10-30
2,2c3a0fcb-e9fd-4e08-bb99-b7ff5d989c2a,a3b26886-ab2c-4421-a6d3-51594aca86fe,6793405462,savings,NGN,1033281.79,2025-12-29
3,e1208c65-7313-4023-811b-264d30d4a66a,a3b26886-ab2c-4421-a6d3-51594aca86fe,4536808148,solo,NGN,2021.75,2025-12-01
4,952c7b0c-2287-4ccf-80e0-9a1149efa6ec,a3b26886-ab2c-4421-a6d3-51594aca86fe,8762233309,current,NGN,3352784.62,2025-03-31

In [13]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        3000 non-null   str
 1   first_name         3000 non-null   str
 2   last_name          3000 non-null   str
 3   full_name          3000 non-null   str
 4   gender             3000 non-null   str
 5   age                3000 non-null   int64
 6   date_of_birth      3000 non-null   str
 7   bvn                3000 non-null   int64
 8   nin                3000 non-null   int64
 9   phone_number       3000 non-null   int64
 10  telco_provider     3000 non-null   str
 11  email              3000 non-null   str
 12  state_of_origin    3000 non-null   str
 13  residential_state  3000 non-null   str
 14  banking_branch     3000 non-null   str
 15  onboarding_date    3000 non-null   str
dtypes: int64(4), str(12)
memory usage: 764.8 KB

In [15]:
transactions.columns

Index(['transaction_id', 'transaction_reference_number', 'account_id',
       'channel', 'device_id', 'counterparty_bank', 'narration',
       'transaction_type', 'amount', 'currency', 'transaction_balance',
       'transaction_status', 'failure_reason', 'is_fraud_score',
       'fraud_explainability_trace', 'merchant_category', 'merchant_name',
       'salary_detected', 'car_loan_signal_score', 'recommended_product',
       'transaction_timestamp'],
      dtype='str')

In [18]:
transactions['amount']

0          23391.91
1          28270.78
2          96879.45
3         176926.70
4          21819.87
            ...
184376     79680.52
184377     16019.14
184378    120230.46
184379    116061.21
184380     11971.67
Name: amount, Length: 184381, dtype: float64

In [5]:
customer_ids = customers["customer_id"]
legit_complaints = complaints[complaints["customer_id"].isin(customer_ids)]

In [6]:
legit_complaints

Empty DataFrame
Columns: [complaint_id, customer_id, linked_transaction_id, linked_reference, department_code, department_name, priority_level, sentiment, complaint_channel, assigned_agent_id, complaint_timestamp, resolution_timestamp, resolution_time_hours, sla_hours_limit, sla_breach_flag, complaint_status, fraud_related, complaint_text, complaint_narration]
Index: []

In [ ]:
transaction_ids = transactions["transaction_id"]

Empty DataFrame
Columns: [complaint_id, customer_id, linked_transaction_id, linked_reference, department_code, department_name, priority_level, sentiment, complaint_channel, assigned_agent_id, complaint_timestamp, resolution_timestamp, resolution_time_hours, sla_hours_limit, sla_breach_flag, complaint_status, fraud_related, complaint_text, complaint_narration]
Index: []

In [7]:
complaints["customer_id"]

0        2b65ee56-991e-4377-9395-69f29ca99cb5
1        2b65ee56-991e-4377-9395-69f29ca99cb5
2        2b65ee56-991e-4377-9395-69f29ca99cb5
3        2b65ee56-991e-4377-9395-69f29ca99cb5
4        485638ae-1b64-442a-a1b7-37bb58823863
                         ...
29582    32781809-b46b-44ae-be18-3cd6d65a17bd
29583    2e286536-dd4f-4cfe-9047-dcd0b03d00b6
29584    2e286536-dd4f-4cfe-9047-dcd0b03d00b6
29585    2e286536-dd4f-4cfe-9047-dcd0b03d00b6
29586    2e286536-dd4f-4cfe-9047-dcd0b03d00b6
Name: customer_id, Length: 29587, dtype: str

In [3]:
complaints

,complaint_id,customer_id,linked_transaction_id,linked_reference,department_code,department_name,priority_level,sentiment,complaint_channel,assigned_agent_id,complaint_timestamp,resolution_timestamp,resolution_time_hours,sla_hours_limit,sla_breach_flag,complaint_status,fraud_related,complaint_text,complaint_narration
0,CMP-000001,2b65ee56-991e-4377-9395-69f29ca99cb5,711a7810-8dd2-4e59-92ae-e45545722f99,TXN725770367753,TSU,Transaction Services Unit,High,angry,branch,TSU_A5,2025-08-11 13:21:04,2025-08-11 17:21:04,4,48,0,escalated,0,This is unacceptable. I was charged ₦16755.14 ...,Customer reported issue regarding transaction ...
1,CMP-000002,2b65ee56-991e-4377-9395-69f29ca99cb5,672bac4e-4836-4184-bd16-04789acf007a,TXN585160219628,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A4,2025-11-08 08:55:52,2025-11-09 13:55:52,29,48,0,open,0,My transfer of ₦36348.8 with reference TXN5851...,Customer reported issue regarding transaction ...
2,CMP-000003,2b65ee56-991e-4377-9395-69f29ca99cb5,14bb542d-2e9d-4f80-8778-828ab894534b,TXN279288074707,COC,Card Operations Center,High,calm,branch,COC_A2,2025-10-13 13:12:38,2025-10-16 10:12:38,69,48,1,escalated,0,Kindly assist. My card was declined even thoug...,Customer reported issue regarding transaction ...
3,CMP-000004,2b65ee56-991e-4377-9395-69f29ca99cb5,7c7deabc-40d1-4c3e-ab96-941ada470014,TXN718789900398,TSU,Transaction Services Unit,High,calm,email,TSU_A5,2025-06-29 04:06:16,2025-07-01 22:06:16,66,48,1,resolved,0,Kindly assist. I was charged ₦98974.46 but the...,Customer reported issue regarding transaction ...
4,CMP-000005,485638ae-1b64-442a-a1b7-37bb58823863,ac84d2c7-5fb8-4413-b15d-c548bb3904ae,TXN304455330967,COC,Card Operations Center,High,angry,branch,COC_A3,2025-02-09 05:53:15,2025-02-09 10:53:15,5,48,0,open,0,This is unacceptable. The ATM transaction of ₦...,Customer reported issue regarding transaction ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29582,CMP-029583,32781809-b46b-44ae-be18-3cd6d65a17bd,73826ca5-1e12-4e2d-9aaf-9713b2974854,TXN611343382133,TSU,Transaction Services Unit,Medium,calm,call_center,TSU_A3,2025-01-18 07:19:50,2025-01-22 02:19:50,91,48,1,open,0,Kindly assist. I was charged ₦48289.39 but the...,Customer reported issue regarding transaction ...
29583,CMP-029584,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,4e987b52-bf9b-4557-9ab2-1da11e20cc49,TXN662493277021,FRM,Fraud Risk Management,Critical,angry,social_media,FRM_A3,2025-12-27 16:51:12,2025-12-29 02:51:12,34,24,1,open,1,This is unacceptable. I believe I am a victim ...,Customer reported issue regarding transaction ...
29584,CMP-029585,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,474a8784-0b09-4478-b3db-e98d700df6c0,TXN340215421577,TSU,Transaction Services Unit,Medium,calm,branch,TSU_A5,2025-09-16 08:24:46,2025-09-19 08:24:46,72,48,1,resolved,0,Kindly assist. This transaction with reference...,Customer reported issue regarding transaction ...
29585,CMP-029586,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,f2df9d73-c56f-4b8a-80e0-908caa63ba85,TXN392130075585,TSU,Transaction Services Unit,Medium,angry,branch,TSU_A4,2025-09-19 01:42:05,2025-09-20 18:42:05,41,48,0,open,0,This is unacceptable. This transaction with re...,Customer reported issue regarding transaction ...
29586,CMP-029587,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,21f841b8-6d7e-4de7-a305-a520cc1318a7,TXN767575190830,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A3,2025-08-30 14:51:38,2025-08-31 02:51:38,12,48,0,open,0,I was charged ₦16019.14 but the transaction fa...,Customer reported issue regarding transaction ...

In [19]:
complaints.head()

,complaint_id,customer_id,account_id,linked_transaction_id,linked_reference,department_code,department_name,priority_level,sentiment,complaint_channel,assigned_agent_id,complaint_timestamp,resolution_timestamp,resolution_time_hours,sla_hours_limit,sla_breach_flag,complaint_status,fraud_related,complaint_text
0,CMP-000001,8f3e4455-fb99-420d-9af1-0218c0d1a3d8,53af8575-a6cc-46c3-ae7b-a0598002945e,3af9c6c2-9620-4502-ac9c-d2413f07aa4b,TXN479423381446,TSU,Transaction Services Unit,Medium,neutral,email,TSU_A2,2025-12-12 09:45:44,2025-12-14 21:45:44,60,48,1,escalated,0,My transfer of ₦31535.91 with reference TXN479...
1,CMP-000002,8f3e4455-fb99-420d-9af1-0218c0d1a3d8,53af8575-a6cc-46c3-ae7b-a0598002945e,de52dcae-be64-4c02-98b8-02c6fc5bfd48,TXN870404520291,COC,Card Operations Center,High,calm,social_media,COC_A3,2025-08-20 08:56:08,2025-08-23 04:56:08,68,48,1,escalated,0,Kindly assist. The ATM transaction of ₦39234.2...
2,CMP-000003,8f3e4455-fb99-420d-9af1-0218c0d1a3d8,53af8575-a6cc-46c3-ae7b-a0598002945e,fccc2faa-731e-422b-ad17-5972239a393b,TXN916409847607,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A4,2025-07-22 03:40:19,2025-07-25 20:40:19,89,48,1,resolved,0,This transaction with reference TXN91640984760...
3,CMP-000004,8f3e4455-fb99-420d-9af1-0218c0d1a3d8,53af8575-a6cc-46c3-ae7b-a0598002945e,04f3cde2-8ee1-45d6-bff8-7c2c55e68b8d,TXN690850440670,TSU,Transaction Services Unit,High,calm,social_media,TSU_A5,2026-01-19 20:48:40,2026-01-21 12:48:40,40,48,0,open,0,Kindly assist. I was charged ₦1941.39 but the ...
4,CMP-000005,8f3e4455-fb99-420d-9af1-0218c0d1a3d8,53af8575-a6cc-46c3-ae7b-a0598002945e,4ddbc424-f166-4e31-9bfd-424779c6fc22,TXN891427564629,TSU,Transaction Services Unit,Medium,neutral,email,TSU_A5,2025-06-27 07:49:06,2025-06-28 13:49:06,30,48,0,resolved,0,My transfer of ₦15168.69 with reference TXN891...

In [20]:
complaints["sentiment"].value_counts()

sentiment
neutral    10807
angry      10481
calm        8252
Name: count, dtype: int64

In [4]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 6723 entries, 0 to 6722
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       6723 non-null   str
 1   customer_id      6723 non-null   str
 2   account_number   6723 non-null   int64
 3   account_type     6723 non-null   str
 4   currency         6723 non-null   str
 5   current_balance  6723 non-null   float64
 6   opened_date      6723 non-null   str
dtypes: float64(1), int64(1), str(5)
memory usage: 969.7 KB

In [5]:
accounts["account_type"].value_counts()

account_type
savings    3000
current    3000
solo        723
Name: count, dtype: int64

In [6]:
customers["gender"]

0       female
1       female
2         male
3       female
4         male
         ...
2995    female
2996    female
2997      male
2998      male
2999    female
Name: gender, Length: 3000, dtype: str

In [7]:
transactions

,transaction_id,transaction_reference_number,account_id,channel,device_id,counterparty_bank,narration,transaction_type,amount,currency,...,transaction_status,failure_reason,is_fraud_score,fraud_explainability_trace,merchant_category,merchant_name,salary_detected,car_loan_signal_score,recommended_product,transaction_timestamp
0,8fe7c50c-9d82-42ac-8fe5-961cfd3a3523,TXN942063184144,2b65ee56-991e-4377-9395-69f29ca99cb5,atm,NaN,Access Bank,Enough father size teacher.,credit,23391.91,NGN,...,successful,none,0,normal_pattern,supermarket,Justrite,False,0.0,NaN,2025-11-16 16:49:58
1,8f164f35-2a49-476f-b2bc-6d84cf2420c9,TXN625859696324,2b65ee56-991e-4377-9395-69f29ca99cb5,mobile_app,DEV-62AD23C145CE,PalmPay,We effort see most moment more concern.,credit,28270.78,NGN,...,successful,none,0,normal_pattern,fintech,Paystack,False,0.0,NaN,2026-01-31 18:38:03
2,fe18c524-8089-4149-ad13-d57dd0c200c0,TXN866397377179,2b65ee56-991e-4377-9395-69f29ca99cb5,nibss_transfer,NaN,Union Bank,West trade chair attention.,credit,96879.45,NGN,...,successful,none,0,normal_pattern,education,University Tuition,False,0.0,NaN,2025-08-07 23:04:15
3,2b993b9c-78ad-4900-8626-6909c5fe5735,TXN347056872190,2b65ee56-991e-4377-9395-69f29ca99cb5,mobile_app,DEV-7E22100EEC57,Providus Bank,Brother floor order method name newspaper inside.,debit,176926.70,NGN,...,successful,none,0,normal_pattern,education,Private School Fees,False,0.0,NaN,2026-01-21 21:00:11
4,4c495b17-f7fb-44a5-9f0b-a867619cd65e,TXN874161213052,2b65ee56-991e-4377-9395-69f29ca99cb5,mobile_app,DEV-CAC4A23301DF,Access Bank,Tree enter artist see trip position.,debit,21819.87,NGN,...,successful,none,0,normal_pattern,transport,Uber,False,0.0,NaN,2025-08-23 07:07:48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184376,f2df9d73-c56f-4b8a-80e0-908caa63ba85,TXN392130075585,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,ussd,NaN,Polaris Bank,Job world hair list better society end.,credit,79680.52,NGN,...,successful,none,0,normal_pattern,transport,Bolt,False,0.3,NaN,2025-09-18 16:34:05
184377,21f841b8-6d7e-4de7-a305-a520cc1318a7,TXN767575190830,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,nibss_transfer,NaN,Stanbic IBTC,Region add mouth trade their lawyer.,debit,16019.14,NGN,...,successful,none,0,normal_pattern,restaurants,Cold Stone,False,0.3,NaN,2025-08-30 06:46:38
184378,b069e35f-569e-4f76-b4ea-9d1286001c5d,TXN199058999977,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,pos,NaN,Sterling Bank,Glass type news Republican onto buy put opport...,credit,120230.46,NGN,...,successful,none,0,normal_pattern,fuel,Conoil,False,0.3,NaN,2026-02-19 06:33:59
184379,f38d874d-35da-4ded-8937-03f6486b78de,TXN793370650518,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,web,NaN,Premium Trust Bank,Hot way really resource nor place outside oppo...,credit,116061.21,NGN,...,reversed,none,0,normal_pattern,telecoms,9mobile,False,0.3,NaN,2025-11-03 22:25:33
184380,e35c3c75-4fae-44ec-aa11-b63ed5ba0393,TXN893032813700,2e286536-dd4f-4cfe-9047-dcd0b03d00b6,web,NaN,Fidelity Bank,Present happen camera tree example.,credit,11971.67,NGN,...,failed,compliance_restriction,0,normal_pattern,utilities,DSTV,False,0.3,NaN,2026-01-30 14:25:38